{
    "apiVersion": "v1",
    "kind": "Template",
    "labels": {},
    "metadata": {
        "annotations": {
            "description": "Template pour mettre en place le build d'une branche de code et l'imagestream associé.",
            "iconClass": "icon-nodejs",
            "openshift.io/provider-display-name": "Université Laval",
            "tags": "nodejs",
            "template.openshift.io/bindable": "false"
        },
        "name": "dti-backup-git"
    },
    "objects": [
        {
            "apiVersion": "v1",
            "kind": "ImageStream",
            "metadata": {
                "name": "${NAME}",
                "annotations": {
                    "description": "Keeps track of changes in the application image"
                }
            }
        },
        {
            "apiVersion": "v1",
            "kind": "BuildConfig",
            "metadata": {
                "annotations": {
                    "description": "Defines how to build the application",
                    "template.alpha.openshift.io/wait-for-ready": "true"
                },
                "name": "${NAME}"
            },
            "spec": {
                "source": {
                    "type": "Git",
                    "git": {
                        "uri": "${GIT_URI}",
                        "ref": "${GIT_REF}"
                    }
                },
                "output": {
                    "to": {
                        "kind": "ImageStreamTag",
                        "name": "${NAME}:latest"
                    }
                },
                "strategy": {
                    "dockerStrategy": {}
                },
                "resources": {
                    "limits": {
                        "cpu": "2",
                        "memory": "2Gi"
                    }
                },
                "triggers": [
                    {
                        "type": "ImageChange"
                    },
                    {
                        "type": "ConfigChange"
                    },
                    {
                        "type": "GitHub",
                        "github": {
                            "secret": "${GITHUB_WEBHOOK_SECRET}"
                        }
                    }
                ]
            }
        }
    ],
    "parameters": [
        {
            "name": "NAME",
            "displayName": "Name",
            "description": "The name assigned to all of the frontend objects defined in this template.",
            "required": true,
            "value": "dti-backup-git"
        },
        {
            "name": "GIT_URI",
            "displayName": "Git Repository URI",
            "description": "The URI of the Git repository.",
            "required": true,
            "value": "https://github.com/ulaval/dti-backup-git.git"
        },
        {
            "name": "GIT_REF",
            "displayName": "Git Reference",
            "description": "Set this to a branch name, tag or other ref of your repository if you are not using the default branch.",
            "required": true,
            "value": "master"
        },
        {
            "name": "GITHUB_WEBHOOK_SECRET",
            "displayName": "GitHub Webhook Secret",
            "description": "Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.",
            "from": "[a-zA-Z0-9]{40}",
            "generate": "expression"
        }
    ]
}
