apiVersion: v1
kind: Template
labels: {}
metadata:
  annotations:
    description: Template pour créer un pod permettant d'exécuter la job de backup.
    iconClass: icon-nodejs
    openshift.io/provider-display-name: Université Laval
    template.openshift.io/bindable: "false"
  name: dco-backup-git
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: "${NAME}"
    spec:
      restartPolicy: Never
      containers:
        - name: "${NAME}"
          image: "${IMAGE}"
          # command:
          #   [
          #     "sh",
          #     "-c",
          #     "trap : TERM INT; (while true; do sleep 100; done) & wait",
          #   ]
          command: ["node", "dco-backup-git.js", "-conf=/config/config.json"]
          volumeMounts:
            - name: "backup-folder"
              mountPath: "/backup"

            - name: config
              mountPath: /config
              readOnly: true
          resources:
            limits:
              memory: 1Gi
      volumes:
        - name: "backup-folder"
          persistentVolumeClaim:
            claimName: "dti-backup-git"
        - name: config
          secret:
            secretName: config-dti-backup-git

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to the job.
    required: true
  - name: IMAGE
    displayName: Docker Image
    description: The Docker image to use to run the job.
    value: docker-local.maven.ulaval.ca/fondation/dco/dco-backup-git:latest
