#!/bin/sh
# Script permettant de détruire un build
# Ex: delete-build.cmd <server> <namespace> <gitRef> [token]

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

server=$1
namespace=$2
gitRef=$3
token=$4

objectName="dti-backup-git-$gitRef"
objectName=${objectName//\//-} #Remplace les slash
objectName=${objectName//_/-} #Remplace les underscores

onError()
{
	echo -e "${RED}Script failed.${NC}"
	exit 1
}

oc delete -s=$server -n=$namespace --token=$token --ignore-not-found=true -l=app=$objectName all || goto onerror

echo -e "${GREEN}Script succeeded.${NC}"
