pipeline {
    agent {
        docker {
            image "docker-local.maven.ulaval.ca/ena2/ena2-openshift-client"
            registryUrl 'https://docker-local.maven.ulaval.ca/v2'
            registryCredentialsId 'artifactory-docker-registry-credentials'
        }
    }
    environment {
        token = credentials('openshift-ena2-suiviprojet-dv-token')
        openshiftServer = 'https://pca.exp.ulaval.ca'
        openshiftProject = 'ena2-suiviprojet-dv'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building branch ${branch}'

                script {
                    env.branch = env.BRANCH_NAME
                    env.appName = env.branch.toLowerCase().replace('/', '-').replace('_', '-');
                }

                echo "BRANCH_NAME = ${env.BRANCH_NAME}"
                echo "branch = ${branch}"
                echo "appName = ${appName}"

                script {
                    try {
                        // If application doesn't exist, create it
                        sh "oc get route --server=${openshiftServer} -n=${openshiftProject} ${appName} --token=${token}"
                        echo "Application ${appName} already exists."

                        echo "Starting build of ${appName}..."
                        sh "oc start-build --server=${openshiftServer} -n=${openshiftProject} ${appName} --wait --token=${token}"
                    } catch (e) {
                        echo "The app does not exist on Openshift."
                        // echo "Application ${appName} doesn\'t exists. Creating the app..."
                        // sh "oc new-app ena2-suiviprojet --server=${openshiftServer} -n=${openshiftProject} -p NAME=${appName} -p SOURCE_REPOSITORY_REF=${branch} -l app=${appName} --token=${token}"
                    }
                }
            }
        }
    }
}
