#!/bin/sh
# Allows to delete all resources allocated by this project.
# Ex: ./job-delete <server> <namespace> [token]

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

server=$1
namespace=$2
token=$3

onError()
{
	echo -e "${RED}Script failed.${NC}"
	exit 1
}

oc delete -s=$server -n=$namespace --token=$token --ignore-not-found=true -l=sys=dti-backup-git all || goto onerror

echo -e "${GREEN}Script succeeded.${NC}"
