#!/bin/sh
# Script to initialize a namespace in OpenShift.
# Ex: init-namespace.sh <namespace> <gitRef> [token]

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

server=$1
namespace=$2
gitRef=$3
token=$4

objectName="dti-backup-git-$gitRef"
objectName=${objectName//\//-} #Remplace les slash
objectName=${objectName//_/-} #Remplace les underscores

onError()
{
	echo -e "${RED}Script failed.${NC}"
	exit 1
}

echo "Adding common objects..."
oc new-app -s=$server -n=$namespace --token=$token \
    -f=templates/build.yaml --name=$objectName -l=sys=dti-backup-git,gitref=$gitRef -p=NAME=$objectName -p=GIT_REF=$gitRef || onError

echo -e "${GREEN}Script succeeded.${NC}"


