#!/bin/sh
# Script to initialize a build of this code in Openshift.
# Ex: ./new-build <server> <namespace> <gitRef> [token]

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

server=$1
namespace=$2
gitRef=$3
token=$4

objectName="dti-backup-git-$gitRef"
objectName=${objectName//\//-} #Remplace les slash
objectName=${objectName//_/-} #Remplace les underscores

onError()
{
	echo -e "${RED}Script failed.${NC}"
	exit 1
}

echo "Creating image stream and build config..."
oc new-app -s=$server -n=$namespace --token=$token \
    -f=templates/build.yaml --name=$objectName -l=sys=dti-backup-git,gitref=$gitRef -p=NAME=$objectName -p=GIT_REF=$gitRef || onError

oc logs -s=$server -n=$namespace bc/$objectName --follow || onError
count=$(oc get -s=$server -n=$namespace build/$objectName-1 -o yaml | grep "phase: Complete" | wc -l)

if [ $count != 1 ]
then
    onError
fi

echo -e "${GREEN}Script succeeded.${NC}"


