#!/bin/sh
#Permet d'exécuter le backup sur Openshift - un oc login est nécessaire
#--attach=true permet de voir l'output du pod
#--rm permet de faire le ménage sur openshift

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

server=$1
namespace=$2
gitRef=$3
token=$4

objectName="dti-backup-git-$gitRef"
objectName=${objectName//\//-} #Remplace les slash
objectName=${objectName//_/-} #Remplace les underscores

oc run dti-backup-git-$objectName -s=$server -n=$namespace --attach=true --image=dti-backup-git-$gitRef --restart=Never --rm
